# Site settings
title: Adam Phillips-Silver | Technologist
email: labonvie07@gmail.com
description: "A site about life, web development, and technology."
baseurl: "/mobilelayout"

# Build settings
markdown: kramdown
permalink: pretty
